### ISSUE TITLE
Whyrusleepings Daily Log

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/starlog#1]
Im gonna use this space to log what im working on on a daily basis.

**Comment by whyrusleeping** [comment]
## 12/20/2014

Working on my provides-rewrite branch, making all the tests pass.
Included in this is changing generation of test peers to be deterministic. Ill put it up for PR once this is completed.

**Comment by whyrusleeping** [comment]
## 12/24/2014

Working on rebasing both my `feat/indirect` branch and `provides-rewrite`.  on top of that, im  rereading through all the DHT code once more to make sure its all kosher and there arent any glaring bugs.

**Comment by whyrusleeping** [comment]
Working through some bugs on the DHT, i found that network.DialPeer is hanging... will investigate further.

**Comment by jbenet** [comment]
(Note: it's supposed to wait until a connection is made)

—

**Comment by whyrusleeping** [comment]
## 12/29/14

Addressing PR concerns for `provides-rewrite` and investigating various test failures on jenkins. I almost beleived in magic when i thought docker tests were running on casseopaea when it didnt have docker installed. Im starting to take a look at why the docker network test is failing, and sinking into the bootstrapping code a bit.

**Comment by whyrusleeping** [comment]
## 12/30/14

Dusting off dhthell to try and figure out why ipfs doesnt seem to be able to do anything anymore. The API has changed a bit since then so its gonna take a little bit of finagling.

**Comment by whyrusleeping** [comment]
apparently i like to find bugs in the underlying transport code. maybe its my calling in life?

**Comment by whyrusleeping** [comment]
## 1/1/15

debugging and testing some different muxing libraries with @jbenet, happy we finally got 456 merged in.
