### ISSUE TITLE
Upload icon functionality unclear

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/starlog#19]
- What sort of files can be used? Do they have to be icons? 
- What do they do - is this for each post, for the author, for the blog? Is it publicly viewable?
- Where is this stored? I uploaded a .jpeg and a .png, and both times wasn't able to see the files.

**Comment by krl** [comment]
They can be any file atm, but only images recognized by the browser will be loaded.

**Comment by krl** [comment]
They should also be shown now with the updated readme instructions.

**Comment by RichardLitt** [comment]
Cool. Works with `--unrestricted-api`, image files loading. Eventually the UI should be improved to show that this is a blog-level image for all posts, and suggested filetypes should be given.
