### ISSUE TITLE
jbenet's log

### ISSUE THREAD

**Issue by jbenet** [ipfs/starlog#2]
## 2014-12-19 + 2014-12-20
- migrate `peer.Peer -> peer.ID` -- this involves changing the whole codebase :( -- it's a ton cleaner and have gotten rid of several undeterministic fails. progress: https://github.com/jbenet/go-ipfs/compare/master...peer-restrict
- https://github.com/jbenet/go-ipfs/pull/466

**Comment by jbenet** [comment]
## 2014-12-21 - 28
- merged peer refactor
- wall of bugs.
- https://github.com/jbenet/go-ipfs/pull/473 dht fixes 
- https://github.com/jbenet/go-ipfs/pull/475 fracctx util
- https://github.com/jbenet/go-ipfs/pull/476 fixed race condition in epictest
- https://github.com/jbenet/go-ipfs/pull/477 updated go-peerstream to fix stream closing bug 
- https://github.com/jbenet/go-ipfs/pull/478 start of relaying. not done yet.

**Comment by jbenet** [comment]
(i am still a pumpkin :jack_o_lantern: :christmas_tree: until the 31st morning >.<)

**Comment by whyrusleeping** [comment]
Do we need to send a rescue party?

**Comment by jbenet** [comment]
## 2014-12-31
- :earth_americas: :fireworks: :jack_o_lantern: :arrow_right: :smile: 
- spdystream fixes -- https://github.com/jbenet/go-ipfs/pull/482 (merged)
- worked on p2p net cleanup -- https://github.com/jbenet/go-ipfs/pull/478 (not ready)

**Comment by jbenet** [comment]
## 2015-01-01
- peerstream transports ([muxado](https://github.com/inconshreveable/muxado) + [yamux](https://github.com/hashicorp/yamux)) because spdystream has problems - https://github.com/jbenet/go-ipfs/pull/483 https://github.com/jbenet/go-ipfs/pull/484 -- settled on yamux for now, as it's much faster and robust. (streams with muxado had some data errors, maybe threadsafety bug?)
- CRed https://github.com/jbenet/go-ipfs/pull/456
- finished p2p net cleanup -- https://github.com/jbenet/go-ipfs/pull/478 (RFC)

**Comment by jbenet** [comment]
## 2015-01-02
- fixed blockstore bug -- https://github.com/jbenet/go-ipfs/pull/486 (merged)
- mount fixes! omg yay -- https://github.com/jbenet/go-ipfs/pull/487 (RFC)

**Comment by jbenet** [comment]
## 2015-01-03
- dht + bitswap deep dive on docker test: (this took so many hours): https://github.com/jbenet/go-ipfs/issues/488
- dht fixes: https://github.com/jbenet/go-ipfs/pull/490 (removed utp... without udp we cant nat. need another solution. (udt doesnt work on chromebook))
- merged https://github.com/jbenet/go-ipfs/pull/478 and https://github.com/jbenet/go-ipfs/pull/487
- cleaned up ctx utils:
  - https://godoc.org/github.com/jbenet/go-context/io
  - https://godoc.org/github.com/jbenet/go-context/ext (`WithParents`
  - https://godoc.org/github.com/jbenet/goprocess (another try at ctxgroup)

**Comment by jbenet** [comment]
# 2015-01-(04-05)
- sharness verbose: https://github.com/jbenet/go-ipfs/pull/493 this makes it easy debug sharness problems in CI.
- **various fixes merged: https://github.com/jbenet/go-ipfs/pull/490 this gets all tests passing** (this is huge)

![](http://stream1.gifsoup.com/view/202134/kids-dancing-to-crazy-frog-o.gif)
- https://github.com/jbenet/go-ipfs/pull/426 bootstrap uses dht.bootstrap
- https://github.com/jbenet/go-ipfs/pull/494 sharness rms bootstrap
- https://github.com/jbenet/go-ipfs/pull/495 merging old https://github.com/jbenet/go-ipfs/pull/393 -- but has an error...
- https://github.com/jbenet/go-ipfs/pull/462 rebased and found errs.

**Comment by jbenet** [comment]
## 2015-01-06
- blockservice async exchange.HasBlock - https://github.com/jbenet/go-ipfs/pull/498
- bootstrap add --default option - https://github.com/jbenet/go-ipfs/pull/497
- `multihash` tool - https://github.com/jbenet/go-multihash/tree/master/multihash

**Comment by daviddias** [comment]
:) maybe the starlog repo was really a starlog :)
