### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/starlog#9]
It would be nice to have a more detailed readme that state what Starlog do, and maybe a screenshot.

I'm saying this because even if I follow IPFS development, I have no idea what Starlog is.

**Comment by RichardLitt** [comment]
Agreed. I tried on both the new feature branch for the front end in #8, and on `master`, and got nothing both times. I suspect you need to have IPFS running first. I'm looking into that now. 

@lgierth had the same issue.

**Comment by RichardLitt** [comment]
@MichaelMure Did you run `bower install` and `npm install` first?

**Comment by RichardLitt** [comment]
@MichaelMure Readme is now here! What do you think? Anything you would like to be clearer?

**Comment by MichaelMure** [comment]
The readme is nice, closing this.
